" Pathogen setup
execute pathogen#infect()
syntax on
filetype plugin indent on

" Indent options
set tabstop=4
set shiftwidth=4
set softtabstop=0 expandtab
set autoindent
set smarttab
set number

" Vim Airline
set laststatus=2
set ttimeoutlen=50 

" Color schemes
" Using Molokai with default terminal background
colorscheme molokai
highlight NonText ctermbg=NONE
hi Normal guibg=NONE ctermbg=NONE
highlight LineNr ctermfg=white ctermbg=NONE
